### ISSUE TITLE
Error running unit tests on node version 6 and node version 4

### ISSUE THREAD

**Issue by subeeshcbabu-zz** [indutny/redns#6]
Running unit tests on this module for node version 4 and node version 6 yielded the following result:

```LM-SJN-00876930:redns suchothendav$ npm test

> redns@1.0.0-alpha1 test /Users/suchothendav/GITHUB/redns
> mocha --reporter=spec test/*-test.js && npm run lint



  redns
    1) should lookup github.com
    2) should respect `all: true` option
    3) should respect `family` option
    4) should merge parallel queries


  0 passing (12ms)
  4 failing

  1) redns should lookup github.com:
     Error: Callback must be a function
      at query (dns.js:227:13)
      at lib/redns.js:172:5
```

Looks like the `dns.resolve4` and `dns.resolve6` added `options` argument in version 7. So the line [here](https://github.com/indutny/redns/blob/master/lib/redns.js#L172) complaints about missing `callback`?

**Comment by indutny** [comment]
Sort of fixed in 4fee7b41288df4be6f532181a0814e373260543b. It will fallback to `maxTTL` option on node version < v6.11.0.
